CREATE TABLE IF NOT EXISTS ORDERS (
    id UUID PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL,
    status VARCHAR(100) NOT NULL,
    total DECIMAL(10, 2),
    currency VARCHAR(100) NOT NULL,
    vat VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_ids (
    order_id UUID NOT NULL,
    product_id UUID NOT NULL,
    PRIMARY KEY (order_id, product_id),
    FOREIGN KEY (order_id) REFERENCES ORDERS(id) ON DELETE CASCADE
);