CREATE TABLE IF NOT EXISTS ORDERS (
    id UUID PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL,
    status VARCHAR(100) NOT NULL,
    total DECIMAL(10, 2),
    currency VARCHAR(100) NOT NULL,
    vat VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ORDER_PRODUCTS (

    id UUID PRIMARY KEY NOT NULL,
    name VARCHAR(600) NOT NULL,
    price DECIMAL(10, 2) NOT NULL ,
    sale_price DECIMAL(10, 2),
    sku INTEGER NOT NULL
);