service:
  host:
    name: localhost
    port: 8080
    prefix:
  auth:
    prefix:
    url: http://localhost
  middleware:
    inventory-url: http//${service.host.name}:8325/middleware-inventory

jpa:
  fallback-provider-id: 123123123

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/postgres
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: middleware-service
  flyway:
    enabled: true
    locations: /db/migration/schema
    baseline-on-migrate: true
  kafka:
    bootstrap-servers:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    doc-expansion: none
    path: /middleware-service/swagger

logging:
  level:
    root: INFO
    com.middleware_service: DEBUG
