
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: middleware-service
  flyway:
    enabled: true
    locations: /db/migration/schema
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks

springdoc:
  swagger-ui:
    enabled: true
    path: /middleware-service/swagger

logging:
  level:
    root: INFO
    com.middleware_service: DEBUG
